[package]
name = "bevy_kira_audio"
version = "0.10.0-github.main"
authors = ["Niklas Eicker <hello@nikl.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for dynamic audio"
repository = "https://github.com/NiklasEi/bevy_kira_audio"
homepage = "https://github.com/NiklasEi/bevy_kira_audio"
documentation = "https://docs.rs/bevy_kira_audio"
keywords = ["bevy", "gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "./README.md"
rust-version = "1.56.1"

[features]
default = ["ogg"]
flac = ["kira/flac"]
mp3 = ["kira/mp3"]
ogg = ["kira/ogg"]
wav = ["kira/wav"]
settings_loader = ["ron", "serde"]

[dependencies]
bevy = { version = "0.7", default-features = false }
anyhow = "1.0"
kira = { version = "0.6", default-features = false, features = ["cpal"] }
ron = { version = "0.6.2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
parking_lot = "0.11.0"

[dev-dependencies]
bevy = { version = "0.7", features = ["bevy_gltf", "bevy_winit", "render"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["ogg"]

[[example]]
name = "custom_channel"
path = "examples/custom_channel.rs"
required-features = ["ogg"]

[[example]]
name = "multiple_channels"
path = "examples/multiple_channels.rs"
required-features = ["ogg"]

[[example]]
name = "status"
path = "examples/status.rs"
required-features = ["ogg"]

[[example]]
name = "semantic_duration"
path = "examples/settings_loader.rs"
required-features = ["ogg", "settings_loader"]
