[package]
name = "bevy_improved_audio"
version = "0.1.0"
authors = ["Niklas Eicker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy
bevy = { version = "0.4.0", default-features = false }

# other
anyhow = "1.0"
rodio = { git="https://github.com/NiklasEi/rodio.git" }
parking_lot = "0.11.0"

[features]
mp3 = ["rodio/mp3"]
flac = ["rodio/flac"]
wav = ["rodio/wav"]
vorbis = ["rodio/vorbis"]
wasm = ["rodio/wasm-bindgen"]
