[package]
name = "bevy_improved_audio"
version = "0.1.0"
authors = ["Niklas Eicker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mp3 = ["minimp3"]
vorbis = ["lewton"]
flac = ["claxon"]
wav = ["hound"]

[dependencies]
# bevy
bevy = { version = "0.4.0", default-features = false }
bevy_reflect = {version = "0.4.0"}

# other
anyhow = "1.0"
kira = { version="0.4.1", default-features=false }
parking_lot = "0.11.0"

minimp3 = { version = "0.5.0", optional=true }
claxon = { version = "0.4.3", optional = true }
hound = { version = "3.4.0", optional = true }
lewton = { version = "0.10.1", optional = true }
