[package]
name = "bevy_kira_audio"
version = "0.4.0"
authors = ["Niklas Eicker <hello@nikl.me>"]
edition = "2018"
license = "MIT"
description = "Bevy plugin for dynamic audio"
repository = "https://github.com/NiklasEi/bevy_kira_audio"
homepage = "https://github.com/NiklasEi/bevy_kira_audio"
documentation = "https://github.com/NiklasEi/bevy_kira_audio"
keywords = ["bevy", "gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "./README.md"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mp3 = ["kira/mp3"]
ogg = ["kira/ogg"]
flac = ["kira/flac"]
wav = ["kira/wav"]
example = [
    "bevy/bevy_gltf",
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/bevy_wgpu",
    "ogg"
]

[dependencies]
# bevy
bevy = { version = "0.5.0", default-features = false }
bevy_reflect = { version = "0.5.0", default-features = false }

# other
anyhow = "1.0"
kira = { version = "0.5.2", default-features = false }
parking_lot = "0.11.0"

[dev-dependencies]
winit = "0.24.0"

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["example"]
